[project]
name = "mcp-server-demo"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.10.1",
    "openpyxl>=3.1.5",
    "pandas>=2.3.1",
    "pandas-stubs==2.3.0.250703",
]
